# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shareEat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shareEat
  pod 'Parse'
  pod 'Eureka', '~> 4.0'
  pod 'ImageRow', '~> 3.0'
  pod 'ParseUI'
  pod 'MBProgressHUD'
  pod 'DateToolsSwift'
  pod 'Cosmos', '~> 15.0'
 
  target 'shareEatTests' do
    inherit! :search_paths
        # Pods for testing
  end

  target 'shareEatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
